export interface Term {
  id: string
  name: string
  category: string
  definition: string
  analogy: string
  example: string
  realLifeUse: string
  correlation?: string
  watchOut?: string
  goodRange?: string
  relatedTerms?: string[]
}

// ── MF Terms ────────────────────────────────────────────────────────────────
export const MF_TERMS: Term[] = [
  // ── BASICS ──────────────────────────────────────────────────────────────
  {
    id: 'nav',
    name: 'NAV (Net Asset Value)',
    category: 'Basics',
    definition: 'The per-unit price of a mutual fund — calculated daily as (Total Assets - Liabilities) ÷ Number of Units.',
    analogy: `Like a share price of the fund itself. If Parag Parikh Flexi Cap NAV is ₹83 today, investing ₹83,000 gives you exactly 1,000 units.`,
    example: `You invest ₹50,000 when NAV is ₹100 → you get 500 units. After 5 years NAV is ₹180 → your 500 units are worth ₹90,000. You made ₹40,000 profit.`,
    realLifeUse: `Don't choose a fund because its NAV is "cheap" (₹10 vs ₹200). A ₹200 NAV fund that grew from ₹10 is far better than a ₹10 NAV fund that never moved. Only compare NAV growth (CAGR) — not the absolute NAV number.`,
    correlation: `NAV growth rate = CAGR. Higher CAGR over 5Y means NAV grew faster. NAV falls when markets fall — that's normal.`,
    watchOut: `Never compare NAV across funds. ₹100 NAV is not "expensive" compared to ₹20 NAV. What matters is how much each grew from their starting point.`,
    goodRange: `Any level — only NAV growth rate (CAGR) matters`,
    relatedTerms: ['CAGR', 'AUM', 'SIP'],
  },
  {
    id: 'sip',
    name: 'SIP (Systematic Investment Plan)',
    category: 'Basics',
    definition: `Automating a fixed monthly investment into a mutual fund on a set date regardless of market conditions.`,
    analogy: `Like an EMI, but in your favor. Just as your home loan EMI doesn't stop when property prices fall, your SIP continues buying when markets fall — giving you more units at lower prices.`,
    example: `₹5,000/month SIP for 15 years at 12% CAGR = ₹9L invested → ₹25L final value. The extra ₹16L is pure compounding magic.`,
    realLifeUse: `Set SIP date to 1st or 5th of month (post salary credit). Never stop SIP during market crashes — that's exactly when you're buying cheap. Automate via NACH mandate so it's effortless.`,
    correlation: `SIP returns are measured by XIRR (not CAGR). Your SIP performance improves with higher Volatility — more price swings = more units bought cheap.`,
    watchOut: `Don't pause SIP during market crashes. The best units are bought during crashes. Pausing for "safety" is the classic retail investor mistake.`,
    goodRange: `Minimum 5 years. Ideal 10–20 years. Minimum ₹500/month.`,
    relatedTerms: ['XIRR', 'NAV', 'Volatility', 'CAGR'],
  },
  {
    id: 'aum',
    name: 'AUM (Assets Under Management)',
    category: 'Basics',
    definition: 'Total money invested in a fund by all investors — the fund size.',
    analogy: `Like a restaurant's revenue. A popular restaurant with high daily sales (high AUM) is trusted, but a small speciality restaurant may serve better food.`,
    example: `Parag Parikh Flexi Cap: ₹75,000 Cr AUM. HDFC Small Cap: ₹25,000 Cr AUM. Mirae Asset Emerging Bluechip: paused new SIPs because AUM got too large!`,
    realLifeUse: `For small-cap and mid-cap funds, beware of very large AUM (above ₹20,000 Cr). The manager struggles to deploy capital in small stocks without moving the price themselves.`,
    correlation: `High AUM in large-cap funds = good (stability). High AUM in small-cap funds = risk (manager loses flexibility). Low AUM in new funds = higher risk.`,
    watchOut: `Mirae Asset Emerging Bluechip closed for new SIPs at ₹25,000 Cr — too large to run effectively. This is a real risk.`,
    goodRange: `Large cap: no limit. Mid cap: under ₹30,000 Cr. Small cap: under ₹15,000 Cr is safer.`,
    relatedTerms: ['NAV', 'Fund Category', 'Expense Ratio'],
  },
  {
    id: 'fund-category',
    name: 'Fund Category',
    category: 'Basics',
    definition: `Classification of mutual funds by what they invest in — determines risk, return potential, and who should invest.`,
    analogy: `Like choosing a vehicle. Liquid fund = bicycle (safe, short journey). Large-cap = sedan (steady, comfortable). Small-cap = sports car (thrilling but risky). Hybrid = SUV (balanced).`,
    example: `Large-cap fund (Nifty 100 stocks) → 12-14% CAGR, 15% volatility. Small-cap fund → 16-18% CAGR, 28% volatility. Liquid fund → 6-7% returns, near-zero risk.`,
    realLifeUse: `Match category to your goal. Emergency fund → Liquid fund. Child education in 15 years → Flexi/Small cap. Retirement in 25 years → mix of large + mid cap.`,
    correlation: `Higher risk category (small cap) → higher volatility, higher alpha potential, higher max drawdown. Lower risk (large cap) → stable but lower returns.`,
    watchOut: `Many investors go straight to small-cap funds for "maximum returns" without understanding the 35-50% drawdown risk. Start with large/flexi cap.`,
    goodRange: `Match to time horizon: under 1Y → Debt/Liquid. 3-5Y → Hybrid/Large cap. 7Y+ → Flexi/Mid/Small cap.`,
    relatedTerms: ['Volatility', 'CAGR', 'Max Drawdown', 'AUM'],
  },
  {
    id: 'elss',
    name: 'ELSS (Equity-Linked Saving Scheme)',
    category: 'Basics',
    definition: `Tax-saving equity mutual fund with mandatory 3-year lock-in. Eligible for Section 80C deduction up to ₹1.5 lakh per year.`,
    analogy: `Like a 3-year fixed deposit but in the stock market. You lock money for 3 years, save tax upfront, and get market returns instead of FD rates.`,
    example: `Invest ₹1,50,000 in ELSS → save ₹46,800 in tax (at 30% bracket) immediately. After 3 years at 13% CAGR, ₹1.5L becomes ₹2.15L. Effective post-tax return = extraordinary.`,
    realLifeUse: `Always invest ELSS via SIP, not lump sum in March. Each SIP instalment has its own 3-year lock-in. If you invest ₹12,500/month, after 3 years you can redeem each monthly instalment as it completes.`,
    correlation: `ELSS has shortest lock-in among 80C options. PPF = 15Y. NSC = 5Y. ELSS = 3Y. But ELSS is equity — more risk than others.`,
    watchOut: `Tax saving is front-loaded but LTCG tax applies on gains above ₹1.25L. The net tax benefit is still excellent but factor in LTCG when calculating.`,
    goodRange: `Maximum ₹1.5L per year for full 80C benefit. Use SIP: ₹12,500/month.`,
    relatedTerms: ['SIP', 'CAGR', 'Direct vs Regular', 'LTCG'],
  },
  {
    id: 'nfo',
    name: 'NFO (New Fund Offer)',
    category: 'Basics',
    definition: `A mutual fund's first public offering — like an IPO but for funds, typically launched at ₹10 NAV.`,
    analogy: `Like a new restaurant opening. The buzz is high, the menu looks great, but you have no idea if the food is actually good. Existing restaurants have reviews.`,
    example: `In 2021-22, hundreds of NFOs launched at ₹10 during the bull market. Many investors bought thinking "cheap entry at ₹10". Most underperformed existing funds in the same category.`,
    realLifeUse: `Avoid NFOs unless the fund offers a truly unique category not available elsewhere. Existing funds with 5+ year track records are always a safer choice. The ₹10 NAV is not "cheap".`,
    watchOut: `₹10 NAV is NOT cheap. It's just a starting number. A ₹200 NAV fund that grew from ₹10 is far better than a new ₹10 NAV fund.`,
    goodRange: `Generally avoid NFOs. Exception: genuinely new category or strategy with no alternative.`,
    relatedTerms: ['NAV', 'Fund Category'],
  },
  {
    id: 'growth-vs-dividend',
    name: 'Growth vs IDCW Plan',
    category: 'Basics',
    definition: `Growth plan reinvests all profits into the fund (compounding). IDCW (Income Distribution cum Capital Withdrawal) periodically distributes money to you.`,
    analogy: `Growth = planting a mango tree and letting all fruits fall back into the soil to grow more trees. IDCW = picking mangoes every year and eating them.`,
    example: `₹1L invested in Growth plan at 12% CAGR for 20 years = ₹9.6L. Same in IDCW plan (dividends reduce NAV) with reinvestment = ₹6-7L after taxes. Growth wins.`,
    realLifeUse: `Always choose Growth plan unless you need regular income (post-retirement scenario). Dividends are NOT free money — they come from YOUR NAV and are taxable as income.`,
    watchOut: `Many people choose dividend plans thinking it's "extra income". It's not — the NAV drops by exactly the dividend amount. Plus it's taxed at your income tax slab rate.`,
    goodRange: `Choose Growth plan for all long-term wealth creation goals.`,
    relatedTerms: ['NAV', 'CAGR', 'Expense Ratio'],
  },
  // ── RETURNS ────────────────────────────────────────────────────────────
  {
    id: 'cagr',
    name: 'CAGR (Compound Annual Growth Rate)',
    category: 'Returns',
    definition: `The steady annual growth rate that would give the same end result — a "smoothed" representation of actual (lumpy) returns.`,
    analogy: `Imagine you walked a hilly road from Mumbai to Pune. The distance is 150 km in 15 hours. Your "average speed" was 10 km/h — even though you were sometimes at 5 and sometimes at 15. CAGR is that average speed.`,
    example: `Mirae Asset Large Cap Fund: NAV was ₹21 in Jan 2019, ₹40 in Jan 2024. 5Y CAGR = (40/21)^(1/5) - 1 = 13.8%. This means ₹1L grew to ₹1.93L.`,
    realLifeUse: `Compare 5Y CAGR across funds in the same category. If Nifty 50 gave 12% and your fund gave 10%, your fund underperformed. Switch after 3 consistent years of underperformance.`,
    correlation: `CAGR drives NAV growth. Higher CAGR = faster NAV growth = more wealth. Alpha = your fund CAGR - benchmark CAGR. Rolling returns show CAGR across different time windows.`,
    watchOut: `1Y CAGR is meaningless for equity funds. Always evaluate 3Y+ CAGR. A fund can show 60% 1Y CAGR simply because you're measuring from a market bottom.`,
    goodRange: `Large cap: 12-14% long-term. Mid cap: 14-17%. Small cap: 15-20%. Always compare to category benchmark.`,
    relatedTerms: ['XIRR', 'Rolling Returns', 'Alpha', 'NAV'],
  },
  {
    id: 'xirr',
    name: 'XIRR (Extended Internal Rate of Return)',
    category: 'Returns',
    definition: `The true annualized return for irregular cash flows — the correct way to measure SIP performance.`,
    analogy: `Imagine 10 friends gave you money at different times and you returned it at different times. XIRR calculates what "interest rate" you effectively paid/earned across all those irregular transactions — it's the honest number.`,
    example: `You did ₹5,000/month SIP for 3 years (invested ₹1.8L total). Current value ₹2.3L. XIRR ≈ 18%. But wait — if markets crashed in year 2, some monthly investments were at low prices, boosting XIRR higher than you expected.`,
    realLifeUse: `Check XIRR in your Zerodha/Groww/Kuvera app for your SIP portfolio. This is the only metric that matters for evaluating YOUR personal SIP performance — not the fund's published CAGR.`,
    correlation: `XIRR is always different from CAGR for SIP investors. If you invested at regular intervals and markets were volatile, XIRR can be higher than CAGR (you benefited from rupee cost averaging).`,
    watchOut: `Apps sometimes show simple % return instead of XIRR. Always look specifically for XIRR. Simple % return on SIP is misleading.`,
    goodRange: `10%+ is good. 14%+ is excellent. Compare to category benchmark.`,
    relatedTerms: ['CAGR', 'SIP', 'Rolling Returns'],
  },
  {
    id: 'alpha',
    name: 'Alpha',
    category: 'Returns',
    definition: `The extra return a fund earned above what its benchmark delivered — the fund manager's value addition.`,
    analogy: `Your school exam score vs class average. If average was 70 and you scored 82, your alpha is +12. If you scored 65 with average 70, your alpha is -5 (you did worse than the class).`,
    example: `Nifty 50 gave 12.5% over 5 years. Parag Parikh Flexi Cap gave 17.2%. Alpha = +4.7%. This means the fund manager added ₹47,000 of extra value on every ₹1L invested vs just buying an index fund.`,
    realLifeUse: `Consistently positive alpha (3Y+ period) justifies paying for an active fund's higher expense ratio. Negative or zero alpha = buy a Nifty 50 index fund at 0.1% expense ratio instead.`,
    correlation: `Alpha and Expense Ratio are linked. A 1.5% expense ratio is justified only if alpha is consistently above 2%. If alpha is negative, the manager is destroying value even before fees.`,
    watchOut: `One year of positive alpha means nothing. Require 5Y+ of consistent positive alpha. Many funds show great 1Y alpha after lucky market calls.`,
    goodRange: `Above 0% beats benchmark. Above 2% justifies active fund fees. Above 4% is excellent.`,
    relatedTerms: ['CAGR', 'Benchmark', 'Expense Ratio', 'Rolling Returns'],
  },
  {
    id: 'rolling-returns',
    name: 'Rolling Returns',
    category: 'Returns',
    definition: `Returns calculated for every possible N-year window in the fund's history — the most honest measure of consistency.`,
    analogy: `Imagine testing a cricket player not just in this season, but measuring their batting average for every possible 3-year stretch since their debut. If they average 50+ in 90% of all 3-year periods, they're truly consistent.`,
    example: `Axis Bluechip Fund: 3Y rolling returns show 82% of all 3-year windows gave positive returns with average 13.1%. Worst 3Y window: -4%. Best: 31%. This tells you the realistic range of outcomes.`,
    realLifeUse: `Check rolling returns before choosing a fund. If 90%+ of 3Y windows are positive, you can sleep well knowing short-term market timing barely matters for this fund.`,
    correlation: `Funds with high CAGR but low rolling consistency are dangerous — they had one great run, not sustained excellence. High rolling consistency + decent CAGR beats high CAGR + low consistency.`,
    watchOut: `Many funds show great 5Y CAGR measured from a market bottom. Rolling returns expose this by testing all start points — not just the favorable ones.`,
    goodRange: `75%+ positive 3Y windows is good. 85%+ is excellent. 60% or below = unreliable.`,
    relatedTerms: ['CAGR', 'Volatility', 'Benchmark', 'Sharpe Ratio'],
  },
  {
    id: 'benchmark',
    name: 'Benchmark',
    category: 'Returns',
    definition: `The market index your fund is evaluated against — the minimum return you could have got without paying for active management.`,
    analogy: `Your employee's performance review benchmark. A sales employee should beat the team's average. If the benchmark (team average) is 10 deals/month and they do 8, they're underperforming.`,
    example: `Large-cap fund benchmark = Nifty 100 TRI (Total Return Index, including dividends). Flexi cap = Nifty 500 TRI. Midcap = Nifty Midcap 150 TRI. Always compare to TRI, not Price Index.`,
    realLifeUse: `When a fund says "beat the Nifty", always verify: was it Nifty TRI (with dividends) or just the Nifty price index? TRI is 1.5-2% higher annually. Many funds that claim to "beat Nifty" actually lose to Nifty TRI.`,
    watchOut: `"Benchmark" and "category average" are different. A fund can beat category average but still lose to its actual benchmark index. Always check against the index.`,
    goodRange: `Fund return should consistently exceed benchmark over 3Y+ periods.`,
    relatedTerms: ['Alpha', 'CAGR', 'Rolling Returns'],
  },
  {
    id: 'pe-ratio',
    name: 'PE Ratio (Price-to-Earnings)',
    category: 'Returns',
    definition: `Price-to-Earnings ratio tells how many years of current profits you are paying for when buying at today's price.`,
    analogy: `You want to buy a shop that earns ₹1L profit/year. Asking price is ₹20L. PE = 20 — you're paying 20 years of current profit upfront. High PE = betting the shop grows a lot. Low PE = shop available cheap today.`,
    example: `Nifty 50 current PE = 22 (historically 18-22 is fair value). In 2021 Nifty PE hit 40+ (very expensive). After the crash of 2022, PE came to 17 (cheap). Fund PE shows valuation of its underlying portfolio.`,
    realLifeUse: `For equity funds, a lower PE vs category average = the fund manager is buying cheaper stocks. Check fund PE vs category benchmark PE monthly. High PE funds need earnings growth to justify prices.`,
    correlation: `PE connects to CAGR expectations: if PE expands from 15 to 25 + earnings grow 10% → returns can be 30%. If PE contracts from 25 to 15 → even good earnings show poor returns.`,
    watchOut: `PE alone doesn't mean buy or sell. Low PE could mean the business is genuinely bad. High PE can be justified by high growth (tech companies). Context matters.`,
    goodRange: `Fund portfolio PE: compare to its benchmark category average. Under category average = value tilt.`,
    relatedTerms: ['CAGR', 'Alpha', 'Benchmark'],
  },
  // ── RISK ────────────────────────────────────────────────────────────────
  {
    id: 'beta',
    name: 'Beta',
    category: 'Risk',
    definition: `A measure of how much a fund moves relative to the market. Beta 1 = moves exactly with market. Beta 1.2 = 20% more volatile. Beta 0.8 = 20% more stable.`,
    analogy: `Like a ship in the ocean vs a speedboat. Beta 0.8 = cargo ship — ocean waves barely rock it. Beta 1.3 = speedboat — every wave dramatically tilts it. Same ocean, completely different experience.`,
    example: `Nifty falls 10% in one month. Large-cap fund with beta 0.85 = falls ~8.5%. Mid-cap fund with beta 1.25 = falls ~12.5%. Small-cap fund with beta 1.4 = falls ~14%. The aggressive fund hurts much more on the way down.`,
    realLifeUse: `Conservative investors: choose funds with beta below 1.0. Aggressive investors: beta 1.1-1.3 is acceptable for mid/small cap allocations. Never hold high-beta funds as your only investment.`,
    correlation: `Beta is related to Volatility (standard deviation) but different. A fund can have low beta (moves less than market) but still have high absolute volatility if the market itself is volatile.`,
    watchOut: `Low beta doesn't mean safe. A fund with low beta but high alpha = excellent. A fund with low beta and no alpha = probably underperforming.`,
    goodRange: `0.8–1.1 for core portfolio. Up to 1.3 acceptable for small-cap satellite holdings.`,
    relatedTerms: ['Volatility', 'Sharpe Ratio', 'Max Drawdown', 'Alpha'],
  },
  {
    id: 'sharpe-ratio',
    name: 'Sharpe Ratio',
    category: 'Risk',
    definition: `Risk-adjusted return — how much excess return you earned per unit of risk (volatility) taken.`,
    analogy: `Two restaurants both earn ₹1 Cr profit. Restaurant A invested ₹5 Cr capital. Restaurant B invested ₹1 Cr capital. B has a better "Sharpe" — same outcome, far less capital risked.`,
    example: `Fund A: 15% CAGR, 22% volatility, Sharpe = 0.78. Fund B: 13% CAGR, 12% volatility, Sharpe = 1.05. Fund B is more efficient despite lower returns — same money at lower risk.`,
    realLifeUse: `When choosing between two similar funds, prefer the higher Sharpe ratio fund, especially for core portfolio allocation. For short time horizons (3-5 years), high Sharpe matters more than raw returns.`,
    correlation: `Sharpe = (Return - Risk-free rate) / Volatility. Higher return AND lower volatility = better Sharpe. Sharpe below 0.5 means the risk taken is not being rewarded adequately.`,
    watchOut: `Sharpe ratio depends on the time period measured. A fund can show Sharpe 1.5 in a bull market and Sharpe 0.3 in a bear market. Check rolling Sharpe.`,
    goodRange: `Above 0.5 is acceptable. Above 1.0 is good. Above 1.5 is excellent.`,
    relatedTerms: ['Sortino Ratio', 'Volatility', 'Max Drawdown', 'Beta'],
  },
  {
    id: 'sortino-ratio',
    name: 'Sortino Ratio',
    category: 'Risk',
    definition: `Like Sharpe but penalizes only downside volatility (bad days). Upward swings are not counted as "risk".`,
    analogy: `Imagine rating a roller coaster. Sharpe penalizes both terrifying drops AND exhilarating climbs equally. Sortino says: only the terrifying drops are bad — the climbs are what you paid for!`,
    example: `A fund that regularly gives +25% months and occasional -8% months has: high standard deviation (Sharpe looks bad) but low downside deviation (Sortino looks good). This is actually the fund you want to own.`,
    realLifeUse: `For equity funds in bull markets, Sortino is more meaningful than Sharpe. A high-growth fund should have a high Sortino (big up moves, controlled down moves). Use Sortino to separate "good volatile" from "bad volatile" funds.`,
    correlation: `Sortino is almost always higher than Sharpe for good equity funds (because upswings are larger than downswings). A fund where Sortino ≈ Sharpe has symmetric volatility — equally bad up as down.`,
    watchOut: `Don't compare Sortino across different asset classes. Compare only within same fund category.`,
    goodRange: `Above 1.0 is good. Above 1.5 is excellent for equity funds.`,
    relatedTerms: ['Sharpe Ratio', 'Volatility', 'Max Drawdown'],
  },
  {
    id: 'volatility',
    name: 'Volatility / Standard Deviation',
    category: 'Risk',
    definition: `A measure of how much a fund's returns bounce around its average. Higher volatility = wilder swings, both up and down.`,
    analogy: `Compare two cricket batsmen both averaging 45 runs. Player A consistently scores between 35-60. Player B scores either 0 or 90. Same average, completely different reliability. Player B is the "high volatility" option.`,
    example: `Liquid fund volatility: 0.3% monthly. Large-cap: 4% monthly (≈14% annual). Small-cap: 7% monthly (≈25% annual). In practical terms: a ₹10L small-cap investment might swing ₹2.5L in a month.`,
    realLifeUse: `Match volatility to your emotional tolerance. If you'll panic-sell when your ₹10L shows ₹7.5L, stick to low-volatility funds. Volatility becomes your friend in SIP mode — buy more units when prices drop.`,
    correlation: `Volatility connects to Sharpe (lower vol = better Sharpe), Max Drawdown (higher vol = deeper drawdowns), and Beta (higher beta = usually higher vol). All four risk metrics tell the same story from different angles.`,
    watchOut: `Volatility itself is NOT risk of permanent loss. A volatile fund can still give excellent returns. Risk of permanent loss comes from bad quality businesses in the portfolio.`,
    goodRange: `Monthly std dev: under 3% (low), 3-5% (moderate), above 5% (high). Annual: under 14% (low), 14-22% (moderate), above 22% (high).`,
    relatedTerms: ['Sharpe Ratio', 'Max Drawdown', 'Beta', 'Rolling Returns'],
  },
  {
    id: 'max-drawdown',
    name: 'Max Drawdown',
    category: 'Risk',
    definition: `The worst peak-to-trough loss ever experienced — the maximum amount you would have lost if you bought at the worst possible time.`,
    analogy: `You're hiking. You reach a peak of 3,000m, then descend to a valley at 1,800m before climbing again. The max drawdown is 1,200m — the worst you ever fell from your best point.`,
    example: `During March 2020 COVID crash: Nifty fell ~38% peak-to-trough. A mid-cap fund fell 48%. If you had ₹10L just before COVID, it became ₹5.2L in 40 days. Recovery took 7 months. Can you handle that emotionally?`,
    realLifeUse: `Test your emotional resilience against the fund's max drawdown. If you invest ₹10L in a fund with 40% max drawdown, be prepared to see ₹6L on your screen. If that will make you sell, choose a lower max drawdown fund.`,
    correlation: `Max drawdown is closely linked to Volatility (high vol → deep drawdowns) and Fund Category (small cap historically has 50%+ drawdowns). A fund with low max drawdown and decent returns is highly valuable.`,
    watchOut: `Past max drawdown is the minimum future risk — next crash could be worse. Never assume the worst is over just because a fund survived 2020.`,
    goodRange: `Under 20% is good (defensive). 20-35% is moderate (typical large/flexi cap). Above 40% is aggressive (small cap/sectoral).`,
    relatedTerms: ['Volatility', 'Sharpe Ratio', 'Rolling Returns', 'Beta'],
  },
  // ── COST ────────────────────────────────────────────────────────────────
  {
    id: 'expense-ratio',
    name: 'Expense Ratio (TER)',
    category: 'Cost',
    definition: `Annual percentage of your investment deducted daily to cover fund management, admin, and distribution costs — taken automatically from NAV.`,
    analogy: `Like paying a hotel's "resort fee" that gets taken from your wallet every day, invisibly. You don't see the daily deduction but over 20 years it's a massive amount leaving your pocket.`,
    example: `₹10L invested for 20 years at 12% gross return: With 0.5% ER (Direct) → ₹95.4L. With 1.5% ER (Regular) → ₹79.1L. The extra ₹16.3L is entirely from choosing Direct over Regular.`,
    realLifeUse: `Always compare expense ratios within the same fund category. An index fund at 0.1% ER vs an active large-cap fund at 1.2% ER — the active fund must deliver 1.1%+ consistent alpha just to break even.`,
    correlation: `Expense Ratio directly reduces your effective CAGR. 12% gross return - 1.5% ER = 10.5% effective return. Over 20 years, 1.5% reduction equals losing 20-25% of your final wealth.`,
    watchOut: `Expense ratio is charged on your ENTIRE investment, not just the profit. On ₹10L portfolio, 1.5% ER = ₹15,000/year regardless of whether the fund made money or not.`,
    goodRange: `Equity Index: under 0.15%. Active Large cap: under 0.8%. Active Mid cap: under 1.0%. Any Regular plan is always worse than its Direct equivalent.`,
    relatedTerms: ['Direct vs Regular', 'Category Expense Ratio', 'Alpha'],
  },
  {
    id: 'direct-vs-regular',
    name: 'Direct vs Regular Plan',
    category: 'Cost',
    definition: `Direct plan: you invest directly with the AMC, no intermediary. Regular plan: a broker/distributor is in the middle, earning a commission from your expense ratio every year.`,
    analogy: `Regular = booking a hotel through OYO or MakeMyTrip (pays commission). Direct = booking directly on the hotel website (no commission, lower rate). Same room, same quality, 15-20% price difference.`,
    example: `Axis Bluechip Direct Plan: 0.55% expense ratio. Axis Bluechip Regular Plan: 1.64% expense ratio. On ₹50L SIP over 20 years at 12% gross return, this 1.09% difference = ₹75+ lakh extra wealth in Direct.`,
    realLifeUse: `Use Groww, Zerodha Coin, MF Central, or AMC websites directly for Direct plans. If a financial advisor is giving genuine advice and planning, a fee-only advisor model is better than paying hidden commission in Regular plans forever.`,
    correlation: `Regular plan's higher expense ratio directly reduces your CAGR by 0.5-1.5% annually. This is compounded over decades. The commission goes to the distributor/advisor, not to better fund management.`,
    watchOut: `Banks heavily push Regular plans because they earn commission. Even AMFI-registered advisors sometimes push Regular plans. Verify by checking expense ratio — Direct will always be cheaper.`,
    goodRange: `Always choose Direct. No exceptions for long-term investing.`,
    relatedTerms: ['Expense Ratio', 'Category Expense Ratio', 'CAGR'],
  },
  {
    id: 'exit-load',
    name: 'Exit Load',
    category: 'Cost',
    definition: `A penalty fee charged when you redeem units before a specified minimum holding period.`,
    analogy: `Like a gym membership penalty for cancelling early. The gym signed you up expecting 12 months of fees — if you leave in month 3, they charge a cancellation fee. The fund expects you to stay invested.`,
    example: `Most equity funds: 1% exit load if you sell within 1 year. So if you invested ₹1L and it grew to ₹1.2L but you sell in month 11, you pay 1% of ₹1.2L = ₹1,200 as penalty.`,
    realLifeUse: `Before redeeming, always check if the 1-year holding period has passed. For each SIP instalment, the clock starts from that instalment's date. Sell after 12 months of each SIP batch to avoid exit load.`,
    watchOut: `Multiple SIP instalments have multiple exit load windows. Partial redemptions may trigger exit load on the specific units being redeemed (FIFO — First In, First Out applies).`,
    goodRange: `0% exit load funds (liquid, overnight) are best for short-term money. 1% exit load is standard and acceptable for long-term equity funds.`,
    relatedTerms: ['Expense Ratio', 'NAV', 'SIP'],
  },
]

// ── Stock Market Terms ───────────────────────────────────────────────────────
export const STOCK_TERMS: Term[] = [
  // ── BASICS ──────────────────────────────────────────────────────────────
  {
    id: 'stock',
    name: 'Stock / Share',
    category: 'Basics',
    definition: `A unit of ownership in a company. When you buy 1 share of Infosys, you literally own a tiny piece of Infosys and its future profits.`,
    analogy: `Imagine Infosys is a pizza with 420 crore slices. Buying 1 share = owning 1 slice. As Infosys grows, your slice becomes more valuable. If they distribute profits (dividend), you get your slice's portion.`,
    example: `Tata Consultancy Services (TCS) has ~366 crore shares. If TCS earns ₹45,000 Cr profit annually, each share is entitled to ₹45000Cr/366Cr = ~₹122.9 profit. This is EPS (Earnings Per Share).`,
    realLifeUse: `When buying stocks, you're becoming a business owner — not a gambler. Ask: "Is this a good business at a fair price?" Not: "Will this stock go up next week?"`,
    correlation: `Stock price = EPS × PE Ratio. Understanding this formula helps you evaluate whether a stock is cheap or expensive. Price goes up when earnings grow AND/OR when investors are willing to pay more per rupee of earnings (PE expansion).`,
    watchOut: `Never buy a stock just because its price "looks cheap" (₹5 or ₹10). Many ₹5 stocks are expensive at ₹5. Price alone means nothing without earnings context.`,
    goodRange: `No absolute range — evaluate relative to earnings (PE ratio) and growth prospects.`,
    relatedTerms: ['EPS', 'PE Ratio', 'Dividend', 'Market Cap'],
  },
  {
    id: 'nse-bse',
    name: 'NSE vs BSE',
    category: 'Basics',
    definition: `Two Indian stock exchanges where shares are listed and traded. NSE (National Stock Exchange) and BSE (Bombay Stock Exchange, est. 1875 — Asia's oldest).`,
    analogy: `Like two malls in the same city selling the same branded products at identical prices. You can shop from either. NSE has higher footfall (trading volume), BSE has more shops (listed companies).`,
    example: `Same Infosys stock: NSE price = ₹1,420, BSE price = ₹1,420 (always nearly identical due to arbitrage). NSE daily turnover ~₹70,000 Cr. BSE ~₹8,000 Cr. NSE is 9x more liquid.`,
    realLifeUse: `Use NSE for all equity trading — better liquidity, tighter bid-ask spreads, faster execution. BSE is useful for SME stocks and bonds. Most platforms default to NSE automatically.`,
    watchOut: `Some small-cap and SME stocks are only listed on BSE. Liquidity is poor — you might not find a buyer when you want to sell.`,
    relatedTerms: ['Nifty 50', 'Sensex', 'SEBI', 'Demat Account'],
  },
  {
    id: 'nifty-sensex',
    name: 'Nifty 50 & Sensex',
    category: 'Basics',
    definition: `Indices tracking top companies: Nifty 50 = 50 largest NSE stocks. Sensex = 30 largest BSE stocks. They represent the pulse of the Indian economy.`,
    analogy: `Like cricket team rankings. Nifty 50 = Top 50 players by current form (weighted by market cap). If the team is winning (markets rising), Nifty goes up. If star players are injured (companies in trouble), Nifty falls.`,
    example: `Nifty 50 in 2000: 1,600. In 2010: 5,800. In 2020 (pre-COVID): 12,000. Today (~2025): 22,500+. Even sleeping investors who bought a Nifty index fund in 2000 multiplied their money 14x in 25 years.`,
    realLifeUse: `Nifty 50 is your benchmark for equity investments. Your mutual fund should beat Nifty 50 TRI (Total Return Index, which includes dividends) over long periods. If it doesn't, just buy a Nifty index fund.`,
    correlation: `Nifty and Sensex are 95%+ correlated. When one rises, the other rises. The difference is composition — Nifty 50 has 50 stocks vs Sensex 30. Nifty Midcap 150 and Nifty Smallcap 250 are separate indices for smaller companies.`,
    watchOut: `Media often says "markets fell 500 points" — always ask "500 points on which index?" Nifty at 22,000 falling 500 points = 2.3% fall. Same as Nifty falling from 1,000 to 500 (50% crash) in 2001.`,
    goodRange: `Nifty PE 15-22 = fair value. Above 28 = expensive. Below 14 = historically cheap (buy aggressively).`,
    relatedTerms: ['NSE vs BSE', 'PE Ratio', 'Benchmark', 'Market Cap'],
  },
  {
    id: 'ipo',
    name: 'IPO (Initial Public Offering)',
    category: 'Basics',
    definition: `When a private company sells its shares to the public for the first time on a stock exchange.`,
    analogy: `A family-owned chain of 50 restaurants decides to expand. To raise money without taking loans, they sell 30% ownership to the public via IPO. Now strangers own part of their restaurant business.`,
    example: `Zomato IPO (July 2021): Issued at ₹76. Stock hit ₹169 in a month. Then crashed to ₹40 by 2022. LIC IPO (2022): Issued at ₹949. Fell to ₹530 in 6 months. IPOs are not automatic money makers.`,
    realLifeUse: `Retail IPO allotment is lottery-based. Don't apply to IPOs hoping to flip for quick profits. Evaluate IPOs like any other business: Is the business model strong? Are the valuations fair? Is promoter quality good?`,
    watchOut: `IPO timing is chosen by the company when market conditions are favorable to them (i.e., expensive valuation for them). The house always wins in IPO pricing.`,
    goodRange: `Solid IPOs to consider: stable business, profitable, reasonable PE vs peers, strong promoter background.`,
    relatedTerms: ['Stock', 'PE Ratio', 'Market Cap', 'SEBI'],
  },
  {
    id: 'demat',
    name: 'Demat Account',
    category: 'Basics',
    definition: `A digital account that holds your shares electronically — like a bank account but for stocks and mutual funds.`,
    analogy: `Before 1996, stocks were physical certificates (like land deeds). Demat replaced paper with digital entries. Like your music CDs becoming Spotify playlists — same songs, zero physical storage.`,
    example: `Top demat providers: Zerodha (tech-first, ₹0 account charges, ₹20 per trade), Groww (beginner-friendly, zero commission MF), Angel One, HDFC Securities. All are SEBI regulated.`,
    realLifeUse: `Open a Zerodha or Groww account online in 15 minutes using Aadhaar + PAN. Zero brokerage on mutual funds. For stocks: Zerodha charges ₹20 per executed trade (flat fee, no percentage).`,
    watchOut: `Your shares are held by NSDL/CDSL (depositories), not by Zerodha/Groww. Even if your broker goes bankrupt, your shares are safe in the depository. This is a common misconception.`,
    relatedTerms: ['SEBI', 'NSE vs BSE', 'T+1 Settlement'],
  },
  {
    id: 'market-cap',
    name: 'Market Capitalisation',
    category: 'Basics',
    definition: `Total market value of a company = Share Price × Total Shares Outstanding. Tells you the company size in rupees.`,
    analogy: `If your colony has 1,000 apartments each valued at ₹50L, the colony's "market cap" is ₹500 Cr. That's the total price to buy the whole colony at current rates.`,
    example: `Reliance Industries: price ₹2,900 × 670 Cr shares = ₹19.4L Cr market cap (India's largest). Zomato: price ₹200 × 860 Cr shares = ₹1.7L Cr (mid-large cap). A ₹100 Cr revenue company with ₹1,000 Cr market cap is 10x overvalued on sales.`,
    realLifeUse: `Large cap (above ₹20,000 Cr): stable, liquid, lower risk. Mid cap (₹5,000–₹20,000 Cr): higher growth potential, moderate risk. Small cap (below ₹5,000 Cr): highest growth potential, highest risk/illiquidity.`,
    watchOut: `Market cap is not book value (what company owns) or revenue (what it earns). It's purely what investors are willing to pay right now — can be wildly over/under what the business is actually worth.`,
    relatedTerms: ['PE Ratio', 'EPS', 'NSE vs BSE', 'Nifty 50'],
  },
  {
    id: 'dividend',
    name: 'Dividend',
    category: 'Basics',
    definition: `A portion of company profits distributed to shareholders as cash — your share of the business profits deposited directly to your bank account.`,
    analogy: `You co-own a bakery with 1,000 others. After paying all expenses, the bakery earns ₹10L profit. They distribute ₹5L to all co-owners as dividend — your 1 share = ₹500 cash deposited.`,
    example: `ITC Ltd: paid ₹7.75/share dividend in FY2024 on a ₹480 stock price = 1.6% dividend yield. Coal India: ₹25.5/share on ₹480 stock = 5.3% yield — comparable to FD returns plus share price upside.`,
    realLifeUse: `High dividend yield stocks (Coal India, ONGC, NTPC) suit retirees wanting regular income. For wealth creation, prefer companies that reinvest profits for growth rather than paying high dividends.`,
    watchOut: `Dividend is NOT free money. The stock price falls by exactly the dividend amount on ex-dividend date. A ₹10 dividend on a ₹100 stock → stock opens at ₹90 on ex-date.`,
    relatedTerms: ['EPS', 'Dividend Yield', 'Stock', 'PE Ratio'],
  },
  {
    id: 'sebi',
    name: 'SEBI (Securities & Exchange Board of India)',
    category: 'Basics',
    definition: `Stock market regulator — the police force of Indian capital markets. Protects investor interests, regulates exchanges, funds, and brokers.`,
    analogy: `Like the RBI for banks, SEBI is the guardian of stock markets. Just as RBI prevents banks from gambling with your deposits, SEBI prevents listed companies from manipulating stock prices or defrauding investors.`,
    example: `SEBI banned 12 Adani Group entities in 2024 for investigation (temporarily). SEBI caught HDFC AMC's dealer in front-running scandal. SEBI mandated T+1 settlement (shares in demat in 1 day vs 2 days).`,
    realLifeUse: `Always verify: Is your broker SEBI registered? (Check sebi.gov.in). Did your AMC disclose expense ratios? SEBI mandates full transparency. SEBI's investor portal (scores.sebi.gov.in) lets you file complaints against brokers.`,
    relatedTerms: ['NSE vs BSE', 'Demat Account', 'IPO'],
  },
  // ── READING MARKET ──────────────────────────────────────────────────────
  {
    id: 'pe-ratio-stock',
    name: 'PE Ratio (Stock Context)',
    category: 'Reading Market',
    definition: `Price ÷ Earnings Per Share. Tells you how many rupees investors are paying for every ₹1 of the company's annual earnings.`,
    analogy: `You're buying a juice shop for ₹20L that earns ₹1L profit/year. You're paying PE of 20. Is that fair? Depends — if profits will grow 25% per year, yes. If profits will stay flat, you'll wait 20 years to recoup your investment.`,
    example: `HDFC Bank PE = 19 (mature, stable bank). Bajaj Finance PE = 28 (premium for high growth). TCS PE = 29 (steady growth, high quality). Tata Motors PE = 8 (cyclical business, low valuation). Each PE tells a story.`,
    realLifeUse: `Compare PE to: (1) Company's own history (is it cheaper/costlier than usual?), (2) Sector peers, (3) Growth rate (PEG ratio = PE/Growth rate, ideally below 1.5). Never evaluate PE in isolation.`,
    correlation: `PE and EPS are the two components of stock price. If EPS grows 20% but PE stays same, stock goes up 20%. If PE expands from 15 to 22, stock goes up 46% even with zero earnings growth. Bull markets are largely PE expansion.`,
    watchOut: `Don't blindly buy low-PE stocks. Low PE could mean: declining business (PSU banks in 2019), fraud risk, commodity cyclicality. Always understand WHY the PE is low.`,
    goodRange: `Below 15 = potentially cheap. 15-25 = fair for moderate growth. Above 35 = pricing in high growth expectations — risky if growth disappoints.`,
    relatedTerms: ['EPS', 'Market Cap', 'ROE', 'Fundamental Analysis'],
  },
  {
    id: 'eps',
    name: 'EPS (Earnings Per Share)',
    category: 'Reading Market',
    definition: `Net profit of the company divided by number of shares. The profit your single share is entitled to.`,
    analogy: `A pizza shop makes ₹1 Cr profit this year and has 10L pizza loyalty tokens (shares). Each token's share of profit = ₹10 EPS. If next year profit grows to ₹1.5 Cr, EPS = ₹15. Your token becomes more valuable.`,
    example: `TCS FY2024 Net Profit: ₹45,908 Cr. Shares outstanding: 364 Cr. EPS = ₹126. TCS stock price ₹3,750. PE = 3750/126 = 29.8. Is ₹3,750 justified? Only if you believe TCS EPS will grow significantly.`,
    realLifeUse: `Track EPS growth over 5 years. If EPS grew 15% annually for 5 years, it's a compounding machine. Compare EPS growth to stock price growth — if price grew faster than EPS, the stock got more expensive (PE expanded).`,
    watchOut: `"Adjusted EPS" vs "Reported EPS" — companies sometimes exclude one-time costs to show higher adjusted EPS. Always check if EPS is reported (GAAP) or adjusted.`,
    relatedTerms: ['PE Ratio', 'Stock', 'ROE', 'ROCE'],
  },
  {
    id: 'volume',
    name: 'Volume',
    category: 'Reading Market',
    definition: `Number of shares traded in a session. High volume = strong interest (either buying or selling). Low volume moves are less reliable.`,
    analogy: `Imagine a rumour about a restaurant. If 3 friends tell you it's good, you might believe it. If 3,000 people say the same, you definitely go. Volume is the "how many people confirmed" metric for stock moves.`,
    example: `HDFC Bank average daily volume: 2-3 Cr shares. On a big news day (quarterly results), volume might spike to 8-10 Cr shares. Penny stocks might trade 10,000 shares/day — even small buys move the price massively.`,
    realLifeUse: `High volume breakout = a stock clearing a resistance level with large volume is a strong signal. Low volume breakout = often fake/temporary. For small-cap stocks, check if you can sell without moving the price yourself.`,
    watchOut: `Delivery volume vs total volume matters. If 1 Cr shares traded but only 20 Lakh were actual delivery (hold), 80 Lakh were intraday gamblers. Low delivery % = price move may not sustain.`,
    relatedTerms: ['52-week High/Low', 'OHLC', 'Intraday vs Delivery'],
  },
  {
    id: 'ohlc',
    name: 'OHLC & Candlestick Charts',
    category: 'Reading Market',
    definition: `Open-High-Low-Close: the four prices that define each trading session. Candlestick charts visualize this data to show price behavior.`,
    analogy: `OHLC is like a day's weather summary: Morning temperature (Open), Max temperature (High), Min temperature (Low), Evening temperature (Close). A candle shows the day's entire story in one bar.`,
    example: `Green candle: Open ₹100, High ₹108, Low ₹98, Close ₹106. Red candle: Open ₹100, High ₹104, Low ₹90, Close ₹92. Green = buyers won the day. Red = sellers dominated.`,
    realLifeUse: `For beginners, check only the weekly or monthly candles — don't get lost in daily noise. A series of green candles = trend up. Long red candles with high volume = selling pressure. "Doji" (tiny body) = indecision.`,
    watchOut: `Technical patterns work on aggregate — not on individual stocks every time. Never make buy/sell decisions based on a single candle pattern.`,
    relatedTerms: ['Volume', 'RSI', 'Moving Average', 'Support Resistance'],
  },
  {
    id: 'delivery-pct',
    name: 'Delivery %',
    category: 'Reading Market',
    definition: `Percentage of total traded volume that resulted in actual delivery to demat accounts (long-term buyers vs intraday traders).`,
    analogy: `Imagine 100 people entered a supermarket. 70 actually bought groceries (delivery buyers). 30 just window-shopped and left (intraday traders). Delivery % = 70%. High delivery means real conviction.`,
    example: `Stock A: 60 Lakh shares traded, 45 Lakh delivery = 75% delivery (strong buying). Stock B: 60 Lakh shares traded, 8 Lakh delivery = 13% (mostly intraday speculation). Stock A's move is more credible.`,
    realLifeUse: `When a stock breaks out with high delivery %, it suggests genuine institutional or retail buying intent. Look for stocks with consistent 50%+ delivery on rising price days as entry candidates.`,
    relatedTerms: ['Volume', 'FII DII', 'Intraday vs Delivery'],
  },
  {
    id: '52week',
    name: '52-Week High & Low',
    category: 'Reading Market',
    definition: `Highest and lowest price the stock has traded at in the last 52 weeks (1 year). Key psychological levels for traders and investors.`,
    analogy: `Like an annual school exam marks range. If a student always scores 70-85, and suddenly scores 90, that's a new 52-week high — exceptional performance. If they score 50, that's near the 52-week low — maybe something is wrong.`,
    example: `HDFC Bank 52W High: ₹1,794. 52W Low: ₹1,362. Current: ₹1,620. It's trading 10% below its high but 19% above its low — in the upper half of its range, healthy.`,
    realLifeUse: `Stocks making new 52-week highs with high volume often continue rising (momentum). Stocks near 52-week lows require fundamental analysis — is it cheap (value opportunity) or declining permanently?`,
    relatedTerms: ['Volume', 'Support Resistance', 'PE Ratio'],
  },
  {
    id: 'pb-ratio',
    name: 'P/B Ratio (Price to Book)',
    category: 'Reading Market',
    definition: `Stock price ÷ Book Value per share. Book value = what the company owns minus what it owes. Tells you whether you're paying more or less than the company's net asset value.`,
    analogy: `A house's book value is its construction cost (₹40L). The market price is ₹60L. P/B = 1.5 — you're paying 1.5x what it cost to build. Banks' P/B is similar: you're paying X times their net loans and deposits.`,
    example: `SBI (PSU bank): P/B = 1.8 (relatively cheap). HDFC Bank: P/B = 2.9 (premium for better quality). Kotak Bank: P/B = 3.8 (highest quality premium). P/B below 1.0 often signals a deep value opportunity or distress.`,
    realLifeUse: `Primarily useful for: banks (lending business), asset-heavy companies (steel, cement), and during market crashes to identify undervalued businesses. Asset-light tech companies (Infosys, TCS) will always have high P/B.`,
    watchOut: `P/B below 1 for banks can mean bad loan quality (NPAs). Always check GNPA (Gross Non-Performing Assets) ratio alongside P/B for banks.`,
    relatedTerms: ['PE Ratio', 'ROE', 'Fundamental Analysis'],
  },
  // ── COMPANY ANALYSIS ────────────────────────────────────────────────────
  {
    id: 'roe',
    name: 'ROE (Return on Equity)',
    category: 'Company Analysis',
    definition: `Net Profit ÷ Shareholders Equity. Measures how efficiently the company generates profit from shareholders' money.`,
    analogy: `You invest ₹10L as equity in a business. If it earns ₹2L profit = 20% ROE. Your friend invests ₹10L in another business, earns ₹1L profit = 10% ROE. Your business is more efficient at using your capital.`,
    example: `Bajaj Finance ROE = 22%+. HDFC Bank ROE = 16%. SBI ROE = 17%. Asian Paints ROE = 28%+. Consistently high ROE (15%+ over 10 years) is a hallmark of high-quality compounding businesses.`,
    realLifeUse: `Look for companies with ROE above 15% consistently for 5+ years. This indicates a moat — the business earns excellent returns on capital and can reinvest at high rates, compounding your wealth.`,
    correlation: `ROE = Net Margin × Asset Turnover × Leverage. High ROE via high leverage (debt) is riskier than high ROE via high margins or efficiency. Check debt-to-equity alongside ROE.`,
    watchOut: `Artificially high ROE can come from excessive debt (financial leverage). Asian Paints has 28% ROE with near-zero debt — that's exceptional quality. A company with 30% ROE but 5x debt is risky.`,
    goodRange: `Above 15% is good. Above 20% consistently is excellent. Compare within sector.`,
    relatedTerms: ['ROCE', 'EPS', 'PE Ratio', 'Debt to Equity'],
  },
  {
    id: 'roce',
    name: 'ROCE (Return on Capital Employed)',
    category: 'Company Analysis',
    definition: `EBIT ÷ Capital Employed. Measures how well the company uses ALL its capital (equity + debt) to generate profit — a more complete measure than ROE.`,
    analogy: `ROE measures how well you use your own money in a business. ROCE measures how well you use ALL money (yours + borrowed). Better ROCE = the company earns more per rupee of total capital deployed.`,
    example: `Infosys ROCE = 42%. This means for every ₹100 of total capital deployed (buildings, computers, working capital), Infosys earns ₹42 operating profit. That's exceptional capital efficiency.`,
    realLifeUse: `ROCE should consistently exceed the company's cost of capital (roughly 10-12%). If ROCE = 8% but the company borrows at 10%, it's actually destroying value. Companies with ROCE 20%+ are wealth creators.`,
    watchOut: `Capital-intensive industries (steel, cement, airlines) structurally have lower ROCE. Compare ROCE only within the same industry.`,
    goodRange: `Above 15% consistently is good. Above 25% is excellent. Must exceed cost of capital.`,
    relatedTerms: ['ROE', 'Debt to Equity', 'PE Ratio', 'EPS'],
  },
  {
    id: 'debt-equity',
    name: 'Debt-to-Equity Ratio',
    category: 'Company Analysis',
    definition: `Total Debt ÷ Shareholders Equity. Measures how much of the business is financed by borrowed money vs owners' money.`,
    analogy: `You buy a house worth ₹1 Cr. You paid ₹25L own money (equity) and borrowed ₹75L (debt). Your D/E = 3x. High leverage means even small problems (income loss, interest rate rise) create big stress.`,
    example: `TCS: Debt/Equity ≈ 0 (debt-free, extraordinary!). HDFC Bank: D/E = 7x (but that's normal for banks — they borrow deposits and lend). Tata Motors: D/E = 2.5x (high, due to JLR acquisition debt). Context matters.`,
    realLifeUse: `For non-financial companies, prefer D/E below 1x. Zero debt companies (TCS, Infosys, HDFC AMC) can survive any economic downturn. High D/E in cyclical industries (steel, real estate) is a red flag.`,
    watchOut: `Banks and NBFCs are supposed to have high D/E (they borrow to lend) — don't apply normal D/E norms to them. For banks, check Tier-1 Capital Adequacy Ratio instead.`,
    goodRange: `Non-financial: under 0.5x is excellent. Under 1x is good. Above 2x needs careful scrutiny.`,
    relatedTerms: ['ROE', 'ROCE', 'Fundamental Analysis', 'Promoter Holding'],
  },
  {
    id: 'promoter-holding',
    name: 'Promoter Holding',
    category: 'Company Analysis',
    definition: `Percentage of the company owned by its founders/promoters. High and stable promoter holding generally signals confidence in the business.`,
    analogy: `If you opened a restaurant and owned 70% of it, you'd be very careful with quality. If you sold off 90% ownership to others, you might not care as much. Promoter holding = how much "skin in the game" founders have.`,
    example: `Eicher Motors (Royal Enfield): Promoter holding 49% — skin in the game. Page Industries (Jockey): 59% promoter holding. Adani Enterprises: 72.6% (very high — but also pledged significantly). Always check pledge %.`,
    realLifeUse: `Red flags: promoter holding DECLINING consistently (they're selling their own stock). Also check pledged % of promoter shares — if promoters pledged 40%+ of their shares as loan collateral, forced selling risk is high.`,
    watchOut: `Very high promoter holding (90%+) means low free float — stock can be easily manipulated. Sweet spot: 40-65% promoter holding, low pledge percentage.`,
    goodRange: `40-65% is ideal. Above 70% may create low float issues. Check pledge % separately — should be below 15%.`,
    relatedTerms: ['Market Cap', 'FII DII', 'Fundamental Analysis'],
  },
  {
    id: 'fii-dii',
    name: 'FII & DII Activity',
    category: 'Company Analysis',
    definition: `FII = Foreign Institutional Investors (global funds buying Indian stocks). DII = Domestic Institutional Investors (Indian funds: LIC, SBI MF, etc.).`,
    analogy: `Think of Indian markets as a cricket ground. FIIs are foreign fans who fly in for big matches (and fly out when it rains — i.e., dollar strengthens or global risk rises). DIIs are the local season ticket holders who stay no matter what.`,
    example: `In Jan 2022, FIIs sold ₹41,323 Cr from Indian markets (biggest monthly outflow) after Fed rate hike fears. Nifty fell 7%. But DIIs bought ₹21,000 Cr, cushioning the fall. DII is India's market stabilizer.`,
    realLifeUse: `When FIIs are selling heavily and markets fall, DIIs (funded by domestic SIP flows) provide a floor. This is why "SIP ke paisa se market supports" is partially true. FII buying = strong validation of India growth story.`,
    watchOut: `FII moves are driven by global factors (dollar, Fed rates, global GDP) — not India's fundamentals. Don't panic when FIIs sell — they often come back.`,
    relatedTerms: ['Nifty 50', 'Volume', 'Market Cap', 'Delivery %'],
  },
  {
    id: 'fundamental-analysis',
    name: 'Fundamental Analysis',
    category: 'Company Analysis',
    definition: `Evaluating a company's true worth by studying its financials, business model, competitive position, and management quality — to find good businesses at fair prices.`,
    analogy: `Before buying a used car, you don't just look at the paint color. You check engine health, service history, accident history, mileage. Fundamental analysis is the "pre-purchase inspection" of a company.`,
    example: `Peter Lynch's method: Find companies you understand (Vikas Ecotech: specialty chemicals you use), check if PE is reasonable vs growth, check if promoter buys their own stock, check if business has a moat (brand, patent, market share).`,
    realLifeUse: `For stocks: read quarterly results, annual report, and MD&A (Management Discussion and Analysis). Focus on: revenue growth, margin trends, cash flow, and debt direction. Avoid companies that always "beat guidance" suspiciously.`,
    watchOut: `Fundamentals take time to reflect in price. A fundamentally strong company can underperform for 2-3 years while the market ignores it. Patience is required.`,
    relatedTerms: ['PE Ratio', 'ROE', 'ROCE', 'EPS', 'Debt to Equity'],
  },
  // ── TRADING CONCEPTS ────────────────────────────────────────────────────
  {
    id: 'intraday-delivery',
    name: 'Intraday vs Delivery',
    category: 'Trading',
    definition: `Intraday: Buy and sell on the same day — you own nothing overnight. Delivery: Buy and hold in demat — you're an actual owner.`,
    analogy: `Intraday = renting a Zomato bicycle for 2 hours. Delivery = buying the bicycle. The cyclist (intraday) needs to return the bike by day's end. The owner (delivery) can ride it for years or sell when price is right.`,
    example: `Intraday: Buy 100 shares of HDFC Bank at ₹1,600 at 9:30am, sell at ₹1,625 at 1pm = ₹2,500 profit (1.56% in 3.5 hours). But also lose ₹2,500 if it goes to ₹1,575. 80%+ intraday traders lose money.`,
    realLifeUse: `For beginners and long-term investors: 100% delivery trades only. Never do intraday until you have 2+ years of market experience, understand technical analysis, and can afford to lose 100% of the amount you trade.`,
    watchOut: `Intraday trading is a full-time professional activity. Studies show 80-90% of intraday traders in India lose money. The ₹20 brokerage per trade adds up — a successful intraday trader must overcome brokerage + spread + STT.`,
    relatedTerms: ['Stop Loss', 'Volume', 'STCG Tax', 'RSI'],
  },
  {
    id: 'stop-loss',
    name: 'Stop Loss',
    category: 'Trading',
    definition: `A pre-set price at which your shares are automatically sold to limit losses. The seatbelt of investing.`,
    analogy: `You're driving. Seatbelt won't prevent the accident, but limits the damage. Stop loss won't prevent stock from falling, but ensures you exit before the loss becomes catastrophic.`,
    example: `You buy HDFC Bank at ₹1,600. Set stop loss at ₹1,520 (5% below). If price falls to ₹1,520, it auto-sells. Maximum loss = ₹80/share = 5%. Without stop loss, the same stock could fall to ₹1,200 (25% loss) if company announces bad results.`,
    realLifeUse: `For short-term trades: always set stop loss before entering a position. 5-7% below buy price for large caps. 8-10% for mid/small caps. For long-term delivery investors: optional — but set mental stop loss if thesis breaks.`,
    watchOut: `Stop loss orders can be triggered by temporary intraday dips. Use "Stop Loss Market" order for immediate execution. Avoid placing stop loss at "obvious" levels where institutions know retail investors have clustered stop losses.`,
    relatedTerms: ['Intraday vs Delivery', 'Support Resistance', 'Position Sizing'],
  },
  {
    id: 'support-resistance',
    name: 'Support & Resistance',
    category: 'Trading',
    definition: `Support = price level where falling stocks typically find buyers (floor). Resistance = price level where rising stocks typically face sellers (ceiling).`,
    analogy: `Imagine Nifty is a tennis ball being bounced. Support is the floor (ball bounces up). Resistance is the ceiling (ball bounces back down). Once the ball breaks through the ceiling, that ceiling becomes the new floor.`,
    example: `Nifty 50 had strong support at 17,000 during 2022 (tested 3 times, bounced each time). When it finally broke below 17,000, it fell rapidly. Infosys resisted at ₹1,600 for months — once it broke above, ₹1,600 became support.`,
    realLifeUse: `For new investors: use support levels as buying opportunities (buy near support, stop loss below support). Use resistance as target levels. Don't buy stocks hitting all-time resistance — better to wait for confirmation breakout with volume.`,
    relatedTerms: ['52-week High/Low', 'Volume', 'Moving Average', 'Stop Loss'],
  },
  {
    id: 'rsi',
    name: 'RSI (Relative Strength Index)',
    category: 'Trading',
    definition: `A momentum indicator (0-100 scale) measuring whether a stock is overbought (above 70) or oversold (below 30). Used to time entries/exits.`,
    analogy: `Like body temperature: 36.8°C is normal. 39°C = fever (overbought, might need to rest). 35°C = too cold (oversold, might bounce back). RSI is the "fever thermometer" of stocks.`,
    example: `Adani Ports RSI hit 82 in Dec 2022 before a sharp correction. HDFC Bank RSI touched 28 in April 2024 (after months of selling) — then rallied 18% in 3 months. Oversold RSI often precedes recovery.`,
    realLifeUse: `RSI below 35 on a fundamentally good large-cap = potential buy opportunity. RSI above 75 on a position you own = consider booking partial profits. Never use RSI alone — confirm with fundamental analysis.`,
    watchOut: `RSI can stay overbought for months in a strong trend. In a bull market, RSI 70 is normal. Always combine RSI with trend direction and fundamental quality.`,
    goodRange: `30-70 = normal zone. Below 30 = oversold (potential buy signal). Above 70 = overbought (potential profit booking zone).`,
    relatedTerms: ['Moving Average', 'OHLC', 'Stop Loss', 'Volume'],
  },
  {
    id: 'moving-average',
    name: 'Moving Average (MA)',
    category: 'Trading',
    definition: `Average price over a specific period — smooths out daily noise to reveal the underlying trend direction.`,
    analogy: `Daily temperature varies wildly. A 7-day moving average of temperature tells you "is it getting hotter or cooler this week?" It removes the noise of one unusually hot/cold day.`,
    example: `Nifty 50 200-day Moving Average (DMA) in Jan 2024 = ~20,000. Nifty at 21,500 = above 200 DMA = bull market. The classic rule: "price above 200 DMA = bull trend, below = bear trend". Stock traders watch 20-DMA, 50-DMA, 200-DMA.`,
    realLifeUse: `Simple rule: Buy quality large-caps when: (1) price above 200 DMA AND (2) 50 DMA crossing above 200 DMA (Golden Cross). Both signals together have very high historical success rate.`,
    watchOut: `Moving averages are lagging indicators — they tell you what happened, not what will happen. Use them to confirm trends, not predict them.`,
    relatedTerms: ['RSI', 'Support Resistance', '52-week High/Low'],
  },
  // ── RISK & TAX ──────────────────────────────────────────────────────────
  {
    id: 'position-sizing',
    name: 'Position Sizing',
    category: 'Risk & Tax',
    definition: `Deciding how much of your total portfolio to allocate to a single stock. The most important risk management tool.`,
    analogy: `Imagine you have 12 eggs (your portfolio). If you put all 12 in one basket and drop it, you lose everything. Position sizing is deciding: max 2 eggs per basket, minimum 6 baskets.`,
    example: `₹5L portfolio, 10% position size rule = max ₹50,000 per stock = 10 stocks minimum. If one stock goes to 0 (yes, it can happen — Yes Bank, Satyam, IL&FS), you lose only 10% of total portfolio.`,
    realLifeUse: `Rule for beginners: Never put more than 5-7% in any single stock. Never put more than 15% in any single sector. As you gain experience, you can concentrate (Buffett puts 30%+ in single stocks, but he's researched them for years).`,
    watchOut: `The biggest losses in stock markets come not from bad stock picks but from too-large position sizes in those bad picks. Risk management > stock selection.`,
    relatedTerms: ['Stop Loss', 'Diversification', 'Market Cap'],
  },
  {
    id: 'stcg-ltcg',
    name: 'STCG & LTCG Tax',
    category: 'Risk & Tax',
    definition: `Profit from stocks/equity MFs taxed at different rates depending on holding period. Short-Term Capital Gains (under 1 year) = 20%. Long-Term Capital Gains (above 1 year, gain above ₹1.25L) = 12.5%.`,
    analogy: `Government gives you a reward for patience. Hold a stock for less than 1 year = government takes 20% of profit (STCG). Hold for more than 1 year = government takes only 12.5% of profit above ₹1.25L (LTCG). Wait longer = pay less tax.`,
    example: `You buy HDFC Bank at ₹1,400, sell at ₹1,700 after 11 months. Gain = ₹300/share × 100 shares = ₹30,000. STCG tax = 20% × ₹30,000 = ₹6,000. If you wait 1 more month, gain under ₹1.25L = ZERO LTCG tax.`,
    realLifeUse: `Before selling a winning position that's 11-12 months old: wait until it crosses 1 year. The tax saving can be significant. For LTCG, first ₹1.25L of gains per financial year is completely tax-free — harvest this limit annually.`,
    watchOut: `Budget 2024 changed rates: STCG went from 15% to 20%. LTCG went from 10% to 12.5%. First ₹1.25L LTCG (up from ₹1L) remains tax-free. Rates can change in future budgets.`,
    goodRange: `Always hold equity for 1+ year to qualify for LTCG. Tax-loss harvesting: sell loss-making positions to offset LTCG gains.`,
    relatedTerms: ['ELSS', 'LTCG', 'Intraday vs Delivery', 'Demat Account'],
  },
  {
    id: 'stt-dp',
    name: 'STT & DP Charges',
    category: 'Risk & Tax',
    definition: `STT (Securities Transaction Tax) = mandatory tax on every equity trade. DP Charges = Depository Participant fee when you sell/transfer shares from your demat.`,
    analogy: `Like toll tax on highways. Every time you drive (trade stocks), you pay a small toll whether you profit or not. These small charges add up significantly for frequent traders.`,
    example: `STT on delivery sell = 0.1% of sale value. Sell ₹1L of stocks = ₹100 STT. Zerodha DP charge = ₹13.5 + 18% GST = ₹16 per stock per day of selling (regardless of quantity). Zerodha brokerage = ₹20 per order.`,
    realLifeUse: `Calculate your true cost before trading: Brokerage + STT + DP charges + SEBI turnover fee + Exchange fee. A trader doing 10 buy-sell cycles/month on ₹1L capital easily spends ₹500-800/month in charges — before any profit.`,
    watchOut: `Intraday STT is much lower (0.025% only on sell side) than delivery (0.1% on sell). But intraday traders still get hit by brokerage, spread, and the psychological cost of constant monitoring.`,
    relatedTerms: ['Intraday vs Delivery', 'STCG & LTCG', 'Demat Account'],
  },
  {
    id: 't1-settlement',
    name: 'T+1 Settlement',
    category: 'Risk & Tax',
    definition: `Shares bought today (T) are credited to your demat account by next business day (T+1). SEBI moved India from T+2 to T+1 in 2023 — making India the fastest settling equity market globally.`,
    analogy: `You buy 100 kg of rice today from a wholesale market. Earlier: delivery after 2 days (T+2). Now: delivery tomorrow (T+1). India made this faster than USA (T+1.5 effective) and most European markets.`,
    example: `Buy HDFC Bank shares on Monday → shares in your demat by Tuesday evening. This means: if you sell shares bought on Monday, wait until Tuesday to avoid settlement issues. Selling before delivery = "short selling" (risky).`,
    realLifeUse: `For buy-sell strategies: you can buy and sell on the same day (intraday) — settlement netting happens automatically. For options, settlement is same-day on expiry. For delivery trades, count business days (not calendar days).`,
    relatedTerms: ['Demat Account', 'NSE vs BSE', 'SEBI'],
  },
]

export const MF_CATEGORIES = ['Basics', 'Returns', 'Risk', 'Cost'] as const
export const STOCK_CATEGORIES = ['Basics', 'Reading Market', 'Company Analysis', 'Trading', 'Risk & Tax'] as const

export const MF_BEGINNER_STEPS = [
  { step: 1, title: 'Complete KYC Online', desc: `Go to MF Central (mfcentral.com) or any AMC website. Complete KYC using Aadhaar + PAN. Takes 10 minutes, done once for life.` },
  { step: 2, title: 'Choose Direct Plan App', desc: `Open account on Zerodha Coin, Groww, or Kuvera. These show Direct plans (lower expense ratio). Avoid banks — they push Regular plans.` },
  { step: 3, title: 'Start with One Fund', desc: `Begin with a large-cap index fund (Nifty 50 or Nifty 100 index fund). Learn, observe 6 months, then diversify. Don't start with 5 funds.` },
  { step: 4, title: 'Set SIP on Salary Date', desc: `Automate ₹1,000–₹5,000/month SIP on 5th of month (post salary credit). Set NACH mandate. Never touch it for 5+ years.` },
  { step: 5, title: 'Ignore Daily NAV Changes', desc: `Check your portfolio once every 3 months. Not daily. Markets will fall 20-30% periodically — that's normal. Your SIP buying more units at low price is a feature, not a bug.` },
  { step: 6, title: 'Increase SIP Annually', desc: `Every January, increase SIP by 10-15% (Step-Up SIP). ₹5,000/month growing by 10% yearly creates dramatically more wealth than flat ₹5,000.` },
]

export const STOCK_BEGINNER_STEPS = [
  { step: 1, title: 'Open Demat Account First', desc: `Open Zerodha or Groww account online using Aadhaar + PAN. Zero brokerage on MFs, ₹20 flat on stock trades. Avoid bank brokerage accounts — expensive.` },
  { step: 2, title: 'Start with Nifty ETF', desc: `Buy Nippon India Nifty 50 BeES or SBI Nifty 50 ETF before buying individual stocks. Learn how markets move without individual company risk.` },
  { step: 3, title: 'Read One Annual Report', desc: `Pick a company you understand (Asian Paints, ITC, HDFC Bank). Read their latest annual report. Understand revenue, profit trend, debt, and what management is saying.` },
  { step: 4, title: 'Never Buy on Tips', desc: `"Sure-shot" stock tips on WhatsApp/Telegram are illegal. SEBI prosecutes stock tippers. Tips work for the tipper (they exit while you buy). Do your own research.` },
  { step: 5, title: 'Start Small, Diversify', desc: `Start with ₹10,000–₹50,000 total. 5-7 stocks maximum initially. Large-cap only (Nifty 50 constituents). Never put more than 10% in one stock.` },
  { step: 6, title: 'Avoid F&O Completely', desc: `Futures and Options (derivatives) are for professional traders. 90%+ of F&O traders lose money. SEBI data shows only 11% of F&O traders profit. Stay away for 2+ years.` },
  { step: 7, title: 'Set Stop Losses Always', desc: `Before buying any stock, decide: "At what price will I exit if I'm wrong?" Set this as stop loss. Protecting capital is more important than making profit.` },
  { step: 8, title: 'Tax Efficiency Matters', desc: `Hold for 1+ year to qualify for LTCG (12.5% tax vs STCG 20%). First ₹1.25L LTCG is tax-free annually. Harvest this benefit by selling and rebuying after 1 year.` },
]
